/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.yogadev.SecurityApplication;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        SecurityApplication classUnderTest = new SecurityApplication();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
